### ISSUE TITLE
rescala for scala 2.11 errors out with java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less

### ISSUE THREAD

**Issue by prayagupd** [guidosalva/REScala#27]
I'm using a `.sbt` to play with rescala.

```scala
resolvers += Resolver.bintrayRepo("rmgk", "maven")                                                                                                                                
resolvers += Resolver.bintrayRepo("pweisenburger", "maven")                                            
                                                                                                       
libraryDependencies += "de.tuda.stg" % "rescala_2.11" % "0.19.0" 
```

With sbt `0.13.13`, which is built only against scala 2.10, but you guys do not have rescala_2.10 in here https://dl.bintray.com/rmgk/maven/de/tuda/stg/

my sbt info

```bash
> about
[info] This is sbt 0.13.13
[info] The current project is {file:/Users/prayagupd/possibilities/programming/s2/apple/}apple 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.6
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbt.plugins.Giter8TemplatePlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.6
```

So, when I try to define some `Var`s in sbt console, I get following `java.lang.NoSuchMethodError` error. Which I believe is a scala version issue, as rescala uses 2.11, while the sbt loads 2.10. Correct me if I'm wrong.

```bash
scala> import rescala._
import rescala._

scala> val var1 = Var(1)
java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
	at rescala.parrp.ParRP.preparationPhase(ParRP.scala:61)
	at rescala.engines.PlanImpl$$anonfun$1.apply(PlanImpl.scala:54)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at rescala.engines.PlanImpl$class.plan(PlanImpl.scala:53)
	at rescala.engines.EngineImpl.plan(EngineImpl.scala:13)
	at rescala.engines.PlanImpl$class.subplan(PlanImpl.scala:28)
	at rescala.engines.EngineImpl.subplan(EngineImpl.scala:13)
	at rescala.engines.Ticket$.apply$extension(Ticket.scala:22)
	at rescala.reactives.Var$.apply(sources.scala:75)
	at rescala.engines.Engine$Var$.apply(Engine.scala:37)
	at .<init>(<console>:10)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rmgk** [comment]
You can define the Scala version used by an sbt project, by setting the `scalaVersion` setting.
Try the following sbt file:

```
scalaVersion := "2.12.1"

resolvers += Resolver.bintrayRepo("rmgk", "maven")
resolvers += Resolver.bintrayRepo("pweisenburger", "maven")

libraryDependencies += "de.tuda.stg" %% "rescala" % "0.19.0"
```

I have updated the manual to include this part.

**Comment by prayagupd** [comment]
you are right that specifying scalaVersion to be `2.12.*` would work, or even `2.11.*`. Thanks
